// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiturNetInfrastructure.DBContext;

#nullable disable

namespace MiturNETInfrastructure.Migrations
{
    [DbContext(typeof(MiturNetContext))]
    [Migration("20241031191011_TableTransporte")]
    partial class TableTransporte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.Chofer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Apellido")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Cedula")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("EsConductor")
                        .HasColumnType("bit");

                    b.Property<string>("IdEmpleado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstadoChofer")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Chofer__3214EC07984A763F");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdEstadoChofer");

                    b.ToTable("Chofer", null, t =>
                        {
                            t.HasTrigger("Chofer_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.Estado", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreEstado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Estado__3214EC071945AB43");

                    b.ToTable("Estado", null, t =>
                        {
                            t.HasTrigger("Estado_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.EstadoChofer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActualizadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstadoNavigationId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEstadoNavigationId");

                    b.ToTable("EstadosChofer", t =>
                        {
                            t.HasTrigger("EstadosChofer_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.EstadoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__EstadoSo__3214EC07185155CA");

                    b.HasIndex("IdEstado");

                    b.ToTable("EstadoSolicitud", null, t =>
                        {
                            t.HasTrigger("EstadoSolicitud_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.EstadoVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__EstadoVe__3214EC07DF46176B");

                    b.HasIndex("IdEstado");

                    b.ToTable("EstadoVehiculo", null, t =>
                        {
                            t.HasTrigger("EstadoVehiculo_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("Adjunto")
                        .HasMaxLength(1)
                        .HasColumnType("binary(1)")
                        .IsFixedLength();

                    b.Property<int?>("CantidadPasajeros")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Destino")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaSolicitud")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstadoSolicitud")
                        .HasColumnType("int");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Proposito")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Solicitu__3214EC07571202BD");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdEstadoSolicitud");

                    b.ToTable("Solicitud", null, t =>
                        {
                            t.HasTrigger("Solicitud_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.SolicitudDetalle", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdChofer")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdPasajero")
                        .HasColumnType("int");

                    b.Property<int?>("IdSolicitud")
                        .HasColumnType("int");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Solicitu__3214EC07FC81005B");

                    b.HasIndex("IdChofer");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("SolicitudDetalle", null, t =>
                        {
                            t.HasTrigger("SolicitudDetalle_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdChofer")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstadoVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Placa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Vehiculo__3214EC076A1346CD");

                    b.HasIndex("IdChofer");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdEstadoVehiculo");

                    b.ToTable("Vehiculo", null, t =>
                        {
                            t.HasTrigger("Vehiculo_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetRoleClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", t =>
                        {
                            t.HasTrigger("AspNetRoleClaims_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetRoles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexPage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles", t =>
                        {
                            t.HasTrigger("AspNetRoles_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUserClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", t =>
                        {
                            t.HasTrigger("AspNetUserClaims_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUserLogins", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", t =>
                        {
                            t.HasTrigger("AspNetUserLogins_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUserRoles", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", t =>
                        {
                            t.HasTrigger("AspNetUserRoles_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUserTokens", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", t =>
                        {
                            t.HasTrigger("AspNetUserTokens_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUsers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers", t =>
                        {
                            t.HasTrigger("AspNetUsers_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUsersLoginHistory", b =>
                {
                    b.Property<string>("VUlhid")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("vULHID");

                    b.Property<DateTime>("DLogIn")
                        .HasColumnType("datetime")
                        .HasColumnName("dLogIn");

                    b.Property<DateTime?>("DLogOut")
                        .HasColumnType("datetime")
                        .HasColumnName("dLogOut");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NvIpaddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nvIPAddress");

                    b.HasKey("VUlhid");

                    b.HasIndex("Id");

                    b.ToTable("AspNetUsersLoginHistory", t =>
                        {
                            t.HasTrigger("AspNetUsersLoginHistory_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUsersMenu", b =>
                {
                    b.Property<string>("VMenuId")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("vMenuID");

                    b.Property<int>("ISerialNo")
                        .HasColumnType("int")
                        .HasColumnName("iSerialNo");

                    b.Property<string>("NvFabIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nvFabIcon");

                    b.Property<string>("NvMenuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nvMenuName");

                    b.Property<string>("NvPageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nvPageUrl");

                    b.Property<string>("VParentMenuId")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("vParentMenuID");

                    b.HasKey("VMenuId");

                    b.HasIndex("VParentMenuId");

                    b.ToTable("AspNetUsersMenus", t =>
                        {
                            t.HasTrigger("AspNetUsersMenus_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUsersMenuPermission", b =>
                {
                    b.Property<string>("VMenuPermissionId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vMenuPermissionID");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VMenuId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("vMenuID");

                    b.HasKey("VMenuPermissionId");

                    b.HasIndex("Id");

                    b.HasIndex("VMenuId", "Id")
                        .IsUnique()
                        .HasDatabaseName("IX_AspNetUsersMenuPermission");

                    b.ToTable("AspNetUsersMenuPermission", t =>
                        {
                            t.HasTrigger("AspNetUsersMenuPermission_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUsersPageVisited", b =>
                {
                    b.Property<string>("VPageVisitedId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("vPageVisitedID");

                    b.Property<DateTime>("DDateVisited")
                        .HasColumnType("datetime")
                        .HasColumnName("dDateVisited");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NvIpaddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nvIPAddress");

                    b.Property<string>("NvPageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nvPageName");

                    b.HasKey("VPageVisitedId");

                    b.HasIndex("Id");

                    b.ToTable("AspNetUsersPageVisited", t =>
                        {
                            t.HasTrigger("AspNetUsersPageVisited_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUsersProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VCountry")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vCountry");

                    b.Property<string>("VFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vFirstName");

                    b.Property<string>("VGender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vGender");

                    b.Property<string>("VLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vLastName");

                    b.Property<string>("VPhoto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vPhoto");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsersProfile", t =>
                        {
                            t.HasTrigger("AspNetUsersProfile_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.Setting", b =>
                {
                    b.Property<string>("VSettingId")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("vSettingID");

                    b.Property<string>("VSettingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("vSettingName");

                    b.Property<string>("VSettingOption")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("vSettingOption");

                    b.HasKey("VSettingId");

                    b.ToTable("Setting", t =>
                        {
                            t.HasTrigger("Setting_Trigger");
                        });
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.Chofer", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.Operation.Estado", "IdEstadoNavigation")
                        .WithMany("Choferes")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK__Chofer__IdEstado__7E37BEF6");

                    b.HasOne("MiturNetDomain.Entities.Operation.EstadoChofer", "IdEstadoChoferNavigation")
                        .WithMany("Choferes")
                        .HasForeignKey("IdEstadoChofer")
                        .HasConstraintName("FK__Chofer__IdEstado__7D439ABD");

                    b.Navigation("IdEstadoChoferNavigation");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.EstadoChofer", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.Operation.Estado", "IdEstadoNavigation")
                        .WithMany("EstadosChofer")
                        .HasForeignKey("IdEstadoNavigationId");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.EstadoSolicitud", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.Operation.Estado", "IdEstadoNavigation")
                        .WithMany("EstadosSolicitudes")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK__EstadoSol__IdEst__00200768");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.EstadoVehiculo", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.Operation.Estado", "IdEstadoNavigation")
                        .WithMany("EstadosVehiculos")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK__EstadoVeh__IdEst__01142BA1");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.Solicitud", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.Operation.Estado", "IdEstadoNavigation")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK__Solicitud__IdEst__02FC7413");

                    b.HasOne("MiturNetDomain.Entities.Operation.EstadoSolicitud", "IdEstadoSolicitudNavigation")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdEstadoSolicitud")
                        .HasConstraintName("FK__Solicitud__IdEst__02084FDA");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdEstadoSolicitudNavigation");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.SolicitudDetalle", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.Operation.Chofer", "IdChoferNavigation")
                        .WithMany("SolicitudDetalles")
                        .HasForeignKey("IdChofer")
                        .HasConstraintName("FK_SolicitudDetalle_Chofer");

                    b.HasOne("MiturNetDomain.Entities.Operation.Estado", "IdEstadoNavigation")
                        .WithMany("SolicitudDetalles")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK__Solicitud__IdEst__03F0984C");

                    b.HasOne("MiturNetDomain.Entities.Operation.Solicitud", "IdSolicitudNavigation")
                        .WithMany("SolicitudDetalles")
                        .HasForeignKey("IdSolicitud")
                        .HasConstraintName("FK__Solicitud__IdSol__04E4BC85");

                    b.Navigation("IdChoferNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdSolicitudNavigation");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.Vehiculo", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.Operation.Chofer", "IdChoferNavigation")
                        .WithMany("Vehiculos")
                        .HasForeignKey("IdChofer")
                        .HasConstraintName("FK__Vehiculo__IdChof__06CD04F7");

                    b.HasOne("MiturNetDomain.Entities.Operation.Estado", "IdEstadoNavigation")
                        .WithMany("Vehiculos")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK__Vehiculo__IdEsta__08B54D69");

                    b.HasOne("MiturNetDomain.Entities.Operation.EstadoVehiculo", "IdEstadoVehiculoNavigation")
                        .WithMany("Vehiculos")
                        .HasForeignKey("IdEstadoVehiculo")
                        .HasConstraintName("FK__Vehiculo__IdEsta__07C12930");

                    b.Navigation("IdChoferNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdEstadoVehiculoNavigation");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetRoleClaims", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.UserManagement.AspNetRoles", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUserClaims", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.UserManagement.AspNetUsers", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUserLogins", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.UserManagement.AspNetUsers", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUserRoles", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.UserManagement.AspNetRoles", "Role")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiturNetDomain.Entities.UserManagement.AspNetUsers", "User")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUserTokens", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.UserManagement.AspNetUsers", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUsersLoginHistory", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.UserManagement.AspNetUsers", "IdNavigation")
                        .WithMany("AspNetUsersLoginHistory")
                        .HasForeignKey("Id")
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUsersMenu", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.UserManagement.AspNetUsersMenu", "VParentMenu")
                        .WithMany("InverseVParentMenu")
                        .HasForeignKey("VParentMenuId")
                        .HasConstraintName("FK_AspNetUsersMenu_AspNetUsersMenu");

                    b.Navigation("VParentMenu");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUsersMenuPermission", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.UserManagement.AspNetRoles", "IdNavigation")
                        .WithMany("AspNetUsersMenuPermission")
                        .HasForeignKey("Id")
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUsersMenuPermission_AspNetRoles");

                    b.HasOne("MiturNetDomain.Entities.UserManagement.AspNetUsersMenu", "VMenu")
                        .WithMany("AspNetUsersMenuPermission")
                        .HasForeignKey("VMenuId")
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUsersMenuPermission_AspNetUsersMenu");

                    b.Navigation("IdNavigation");

                    b.Navigation("VMenu");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUsersPageVisited", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.UserManagement.AspNetUsers", "IdNavigation")
                        .WithMany("AspNetUsersPageVisited")
                        .HasForeignKey("Id")
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUsersPageVisited_AspNetUsers");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUsersProfile", b =>
                {
                    b.HasOne("MiturNetDomain.Entities.UserManagement.AspNetUsers", "IdNavigation")
                        .WithOne("AspNetUsersProfile")
                        .HasForeignKey("MiturNetDomain.Entities.UserManagement.AspNetUsersProfile", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUsersProfile_AspNetUsers");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.Chofer", b =>
                {
                    b.Navigation("SolicitudDetalles");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.Estado", b =>
                {
                    b.Navigation("Choferes");

                    b.Navigation("EstadosChofer");

                    b.Navigation("EstadosSolicitudes");

                    b.Navigation("EstadosVehiculos");

                    b.Navigation("SolicitudDetalles");

                    b.Navigation("Solicitudes");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.EstadoChofer", b =>
                {
                    b.Navigation("Choferes");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.EstadoSolicitud", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.EstadoVehiculo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.Operation.Solicitud", b =>
                {
                    b.Navigation("SolicitudDetalles");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetRoles", b =>
                {
                    b.Navigation("AspNetRoleClaims");

                    b.Navigation("AspNetUserRoles");

                    b.Navigation("AspNetUsersMenuPermission");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUsers", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserRoles");

                    b.Navigation("AspNetUserTokens");

                    b.Navigation("AspNetUsersLoginHistory");

                    b.Navigation("AspNetUsersPageVisited");

                    b.Navigation("AspNetUsersProfile");
                });

            modelBuilder.Entity("MiturNetDomain.Entities.UserManagement.AspNetUsersMenu", b =>
                {
                    b.Navigation("AspNetUsersMenuPermission");

                    b.Navigation("InverseVParentMenu");
                });
#pragma warning restore 612, 618
        }
    }
}
